// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


describe('TC_Login_Valid', function() {
this.timeout(30000)
let driver
let vars

beforeEach(async function() {
  driver = await new Builder().forBrowser('chrome').build()
  vars = {}
})
afterEach(async function() {
  await driver.quit();
})
  it('TC_Login_Valid', async function() {
    await driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    await driver.wait(until.elementLocated(By.name("username")), 10000)
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("Admin")
    await driver.wait(until.elementLocated(By.name("password")), 10000)
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("admin123")
    await driver.wait(until.elementLocated(By.css("button[type='submit']")), 10000)
    await driver.findElement(By.css("button[type='submit']")).click()
    await driver.wait(until.elementLocated(By.css(".oxd-topbar-header-breadcrumb")), 10000)
  })
})
