// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


describe('TC_Leave_RequiredValidation', function() {
this.timeout(30000)
let driver
let vars

beforeEach(async function() {
  driver = await new Builder().forBrowser('chrome').build()
  vars = {}
})
afterEach(async function() {
  await driver.quit();
  })
  it('TC_Leave_RequiredValidation', async function() {
    await driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    await driver.wait(until.elementLocated(By.name("username")), 10000)
    await driver.findElement(By.name("username")).sendKeys("Admin")
    await driver.wait(until.elementLocated(By.name("password")), 10000)
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("admin123")
    await driver.wait(until.elementLocated(By.css("button[type='submit']")), 10000)
    await driver.findElement(By.css("button[type='submit']")).click()
    await driver.wait(until.elementLocated(By.linkText("Leave")), 10000)
    await driver.findElement(By.linkText("Leave")).click()
    await driver.wait(until.elementLocated(By.css(".oxd-topbar-body-nav")), 10000)
    await driver.wait(until.elementLocated(By.css(".bi-three-dots-vertical")), 10000)
    await driver.findElement(By.css(".bi-three-dots-vertical")).click()
    await driver.wait(until.elementLocated(By.xpath("//a[normalize-space()='Assign Leave']")), 10000)
    await driver.findElement(By.xpath("//a[normalize-space()='Assign Leave']")).click()
    await driver.wait(until.elementLocated(By.xpath("//button[normalize-space()='Assign']")), 10000)
    await driver.findElement(By.xpath("//button[normalize-space()='Assign']")).click()
    await driver.wait(until.elementLocated(By.xpath("//span[normalize-space()='Required']")), 10000)
    const requiredMessages = await driver.findElements(By.xpath("//span[normalize-space()='Required']"))
    assert(requiredMessages.length >= 1)
  })
})
