// Generated by Selenium IDE, then stabilized for WebDriver execution
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC_Leave_Assign_Valid', function() {
this.timeout(60000)
let driver

beforeEach(async function() {
  driver = await new Builder().forBrowser('chrome').build()
})

afterEach(async function() {
  await driver.quit();
})

async function clearAndType(element, value) {
  await element.click()
  await element.sendKeys(Key.CONTROL, 'a')
  await element.sendKeys(Key.BACK_SPACE)
  await element.sendKeys(value)
  await element.sendKeys(Key.TAB)
}

async function chooseEmployee(searchText) {
  const input = await driver.findElement(By.css('.oxd-autocomplete-text-input input'))
  await input.click()
  await input.sendKeys(searchText)

  await driver.wait(async () => {
    const options = await driver.findElements(By.css('.oxd-autocomplete-option'))

    for (const option of options) {
      try {
        const text = (await option.getText()).trim()
        if (text && text !== 'Searching....' && text !== 'No Records Found') {
          await option.click()
          return true
        }
      } catch (error) {
        return false
      }
    }

    return false
  }, 15000)
}

async function selectLeaveType(leaveType) {
  await driver.findElement(By.css('.oxd-select-text')).click()
  await driver.wait(until.elementLocated(By.css('.oxd-select-option')), 10000)

  const options = await driver.findElements(By.css('.oxd-select-option'))
  for (const option of options) {
    const text = (await option.getText()).trim()
    if (text === leaveType) {
      await option.click()
      return
    }
  }

  throw new Error(`Leave type not found: ${leaveType}`)
}

async function clickTopbarItem(text) {
  await driver.wait(until.elementLocated(By.css('.oxd-topbar-body-nav-tab')), 15000)
  await driver.executeScript(`
    const item = [...document.querySelectorAll('.oxd-topbar-body-nav-tab')]
      .find(element => element.innerText.trim() === arguments[0]);
    if (!item) throw new Error('Topbar item not found: ' + arguments[0]);
    item.click();
  `, text)
}

async function clickAnchor(text) {
  await driver.executeScript(`
    const item = [...document.querySelectorAll('a')]
      .find(element => element.innerText.trim() === arguments[0]);
    if (!item) throw new Error('Anchor not found: ' + arguments[0]);
    item.click();
  `, text)
}

async function getVisibleMessages(selector) {
  const elements = await driver.findElements(By.css(selector))
  const messages = []

  for (const element of elements) {
    if (await element.isDisplayed()) {
      messages.push(await element.getText())
    }
  }

  return messages
}

async function setEmployeeEntitlement() {
  await clickTopbarItem('Entitlements')
  await clickAnchor('Add Entitlements')
  await driver.wait(until.elementLocated(By.xpath("//*[normalize-space()='Add Leave Entitlement']")), 15000)

  await chooseEmployee('Joseph')
  await selectLeaveType('CAN - Bereavement')

  const entitlementInput = await driver.findElement(By.xpath("//label[normalize-space()='Entitlement']/ancestor::div[contains(@class,'oxd-input-group')]//input"))
  await clearAndType(entitlementInput, '50')

  await driver.findElement(By.xpath("//button[normalize-space()='Save']")).click()

  const confirmButtons = await driver.wait(async () => {
    const validationMessages = await getVisibleMessages('.oxd-input-field-error-message')
    if (validationMessages.length > 0) {
      throw new Error(`Entitlement validation failed: ${validationMessages.join(', ')}`)
    }

    const buttons = await driver.findElements(By.xpath("//button[normalize-space()='Confirm']"))
    if (buttons.length > 0) return buttons

    const bodyText = await driver.findElement(By.css('body')).getText()
    if (bodyText.includes('Leave Entitlements')) return []

    return false
  }, 15000)

  if (confirmButtons.length > 0) {
    await confirmButtons[0].click()
  }

  await driver.wait(until.elementLocated(By.css('.oxd-topbar-body-nav-tab')), 15000)
}

async function openAssignLeave() {
  await driver.wait(until.elementLocated(By.css('.bi-three-dots-vertical')), 15000)
  await driver.findElement(By.css('.bi-three-dots-vertical')).click()
  await driver.wait(until.elementLocated(By.xpath("//a[normalize-space()='Assign Leave']")), 10000)
  await driver.findElement(By.xpath("//a[normalize-space()='Assign Leave']")).click()
  await driver.wait(until.elementLocated(By.xpath("//*[normalize-space()='Assign Leave']")), 15000)
}

  it('TC_Leave_Assign_Valid', async function() {
    await driver.get('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    await driver.wait(until.elementLocated(By.name('username')), 15000)
    await driver.findElement(By.name('username')).sendKeys('Admin')
    await driver.wait(until.elementLocated(By.name('password')), 15000)
    await driver.findElement(By.name('password')).sendKeys('admin123')
    await driver.findElement(By.css("button[type='submit']")).click()

    await driver.wait(until.elementLocated(By.linkText('Leave')), 15000)
    await driver.findElement(By.linkText('Leave')).click()
    await setEmployeeEntitlement()

    await openAssignLeave()
    await chooseEmployee('Joseph')
    await selectLeaveType('CAN - Bereavement')

    const dateInputs = await driver.findElements(By.css("input[placeholder='yyyy-dd-mm']"))
    await clearAndType(dateInputs[0], '2026-24-12')
    await clearAndType(dateInputs[1], '2026-24-12')
    await driver.findElement(By.css('textarea')).sendKeys('Automation assign leave')

    await driver.findElement(By.xpath("//button[normalize-space()='Assign']")).click()

    const okButtons = await driver.wait(async () => {
      const validationMessages = await getVisibleMessages('.oxd-input-field-error-message')
      if (validationMessages.length > 0) {
        throw new Error(`Assign Leave validation failed: ${validationMessages.join(', ')}`)
      }

      const failedMessages = await getVisibleMessages('.oxd-toast, .oxd-toast-title, .oxd-toast-content-text')
      if (failedMessages.join(' ').includes('Failed to Submit')) {
        throw new Error('Assign Leave failed to submit')
      }

      const buttons = await driver.findElements(By.xpath("//button[normalize-space()='Ok']"))
      if (buttons.length > 0) return buttons

      const successMessages = failedMessages.join(' ')
      if (successMessages.includes('Success') || successMessages.includes('Successfully')) return []

      return false
    }, 15000)

    if (okButtons.length > 0) {
      await okButtons[0].click()
    }

    await driver.wait(async () => {
      const failedMessages = await getVisibleMessages('.oxd-toast, .oxd-toast-title, .oxd-toast-content-text')
      if (failedMessages.join(' ').includes('Failed to Submit')) {
        throw new Error('Assign Leave failed to submit after confirmation')
      }

      const bodyText = await driver.findElement(By.css('body')).getText()
      return bodyText.includes('Assign Leave') && bodyText.includes('-- Select --')
    }, 15000)

    const visibleValidationMessages = await getVisibleMessages('.oxd-input-field-error-message')
    assert.strictEqual(visibleValidationMessages.length, 0)
  })
})
